version: "3"
services:
  # rym-tags-parser:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: rym-tags-parser
  #   env_file: .env.test
  #   environment:
  #     - MONGO_USER=${MONGO_USER}
  #     - MONGO_PW=${MONGO_PW}
  #     - MONGO_CLUSTERURL=${MONGO_CLUSTERURL}
  #     - DATA_URL=${DATA_URL}
  #     - RMQ_HOST=${RMQ_HOST}
  #     - SERVICE_URL=${SERVICE_URL}
  #   ports:
  #     - "3000:3000"
  #   restart: on-failure
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #     mongodb:
  #       condition: service_healthy
  rabbitmq:
    image: rabbitmq:management-alpine
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 20s
      timeout: 20s
      retries: 5
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/rymdata --quiet
      interval: 20s
      timeout: 20s
      retries: 5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PW}
    restart: unless-stopped
    volumes:
      - rym-tags-mongodata:/data/db
volumes:
  rym-tags-mongodata:
