version: "3"
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PW}
    restart: unless-stopped
    volumes:
      - rym-tags-mongodata:/data/db
  mongoexpress:
    image: mongo-express:latest
    ports:
      - "8084:8081"
    environment:
      - ME_CONFIG_MONGODB_URL="mongodb://${MONGO_USER}:${MONGO_PW}@mongodb:27017"
    restart: always
    depends_on:
      - mongodb
volumes:
  rym-tags-mongodata:
