name: build-and-test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Build app
        run: npm run build

      - name: Create .env file
        run: |
          touch .env

          echo MONGO_PW=${{ secrets.MONGO_PW }} >> .env
          echo MONGO_USER=${{ secrets.MONGO_USER }} >> .env
          echo RMQ_HOST=${{ secrets.RMQ_HOST }} >> .env

          echo MONGO_CLUSTERURL=${{ vars.MONGO_CLUSTERURL }} >> .env
          echo DATA_URL=${{ vars.DATA_URL }} >> .env
          echo SERVICE_URL=${{ vars.SERVICE_URL }} >> .env
          echo PROFILE=${{ vars.PROFILE }} >> .env
          echo TAG=${{ vars.TAG }} >> .env
          echo FROM_PAGE=${{ vars.FROM_PAGE }} >> .env
          echo TO_PAGE=${{ vars.TO_PAGE }} >> .env

      - name: Run tests
        run: npm run test
